// rvo split convert — Module Federation scaffold generator (premium tier).
//
// Takes an approved split plan (JSON from `rvo split --json`, hand-edited by
// the user — that edit step is the "user agrees" gate) and generates a
// Module Federation monorepo under --out:
//
//   <out>/<remote>/  — feature files + the shared files they import,
//                      vite.config.js with @originjs/vite-plugin-federation
//   <out>/shell/     — app shell; router imports of remotes rewritten to
//                      React.lazy federation imports
//   <out>/MIGRATION-NOTES.md — manual steps rvo cannot do for you
//
// Conservative by design, like the rest of rvo:
//   - never touches the source tree; refuses --out inside the project root
//   - relative imports are rewritten only when the target is copied into the
//     same output app; cross-remote imports are left alone and listed as
//     manual work instead of being silently "fixed"
//   - the federation plugin is NOT added to our dependencies — it is emitted
//     as a manual `npm i -D` step in MIGRATION-NOTES.md
const fs = require('fs');
const path = require('path');
const traverse = require('@babel/traverse').default;
const t = require('@babel/types');
const chalk = require('chalk');
const { parse, loadConfig, readJson } = require('./utils');
const { buildProject, resolveImport } = require('./analyzer');
const { clusterOf } = require('./split');

const posix = p => String(p).split(path.sep).join('/');
const REVIEW = 'Generated by `rvo split convert` — REVIEW before use.';

function readPkg(root) {
  try {
    return readJson(path.join(root, 'package.json'));
  } catch {
    return {};
  }
}

function validatePlan(plan, planPath) {
  if (!plan || typeof plan !== 'object')
    throw new Error(`Plan at ${planPath} is not a JSON object.`);
  if (!Array.isArray(plan.remotes) || !plan.remotes.length)
    throw new Error(
      `Plan at ${planPath} has no remotes. Run \`rvo split --json --output plan.json\` on the app first.`
    );
  for (const r of plan.remotes) {
    if (!r.name || !Array.isArray(r.files) || !r.files.length)
      throw new Error(
        `Plan at ${planPath} has a malformed remote (needs name + files[]).`
      );
    if (!r.entry) throw new Error(`Remote "${r.name}" has no entry file.`);
  }
  if (!plan.shell || !Array.isArray(plan.shell.files))
    throw new Error(`Plan at ${planPath} has no shell.files array.`);
  return plan;
}

function sanitizeName(name) {
  let n = String(name).toLowerCase().replace(/[^a-z0-9_]/g, '_');
  if (/^[0-9]/.test(n)) n = '_' + n;
  return n || 'remote';
}

function capName(name) {
  const s = sanitizeName(name).replace(/^_+/, '');
  return (s.charAt(0).toUpperCase() + s.slice(1)).replace(/[^A-Za-z0-9]/g, '') || 'Remote';
}

// ------------------------------------------------------------------ imports
// Rewrite relative import/export/dynamic-import specifiers whose target is
// copied into the same output app. Returns { code, changed }.
// Surgical: only the specifier string bytes are replaced (via AST loc),
// so formatting, comments and everything else survive untouched.
function rewriteRelativeImports(code, srcAbs, destAbs, mapTarget) {
  let ast;
  try {
    ast = parse(code, srcAbs);
  } catch {
    return { code, changed: false };
  }
  const edits = [];
  const handle = node => {
    const spec = node.value;
    if (typeof spec !== 'string' || !spec.startsWith('.')) return;
    const target = resolveImport(srcAbs, spec);
    if (!target) return;
    const newAbs = mapTarget(target);
    if (!newAbs) return;
    let rel = posix(path.relative(path.dirname(destAbs), newAbs));
    if (!rel.startsWith('.')) rel = './' + rel;
    if (rel !== spec) edits.push({ start: node.start + 1, end: node.end - 1, text: rel });
  };
  traverse(ast, {
    ImportDeclaration(p) {
      if (p.node.source) handle(p.node.source);
    },
    ExportNamedDeclaration(p) {
      if (p.node.source) handle(p.node.source);
    },
    ExportAllDeclaration(p) {
      if (p.node.source) handle(p.node.source);
    },
    CallExpression(p) {
      const callee = p.node.callee;
      const arg = p.node.arguments[0];
      if (
        arg && t.isStringLiteral(arg) &&
        (t.isImport(callee) || t.isIdentifier(callee, { name: 'require' }))
      ) {
        handle(arg);
      }
    },
  });
  if (!edits.length) return { code, changed: false };
  edits.sort((a, b) => b.start - a.start);
  let out = code;
  for (const e of edits) out = out.slice(0, e.start) + e.text + out.slice(e.end);
  return { code: out, changed: true };
}

// ------------------------------------------------------------------ collect
// BFS from a remote's files over local imports. Feature files of this remote
// are copied under src/ (cluster prefix stripped); shared files they reach
// go under src/shared/. Anything else (shell files, other features' files)
// is NOT copied — recorded as cross-boundary imports for the notes.
function collectAppFiles({ fileAbsList, srcDir, project, rootAbs, kind, clusterName }) {
  const copyMap = new Map(); // source abs -> dest rel (posix, relative to app dir)
  const cross = []; // { from, spec, target, targetKind }
  const destFor = abs => {
    const srcRel = posix(path.relative(srcDir, abs));
    const c = clusterOf(srcRel);
    if (kind === 'remote') {
      if (c.kind === 'feature' && c.name === clusterName) {
        return 'src/' + srcRel.split('/').slice(c.depth).join('/');
      }
      if (c.kind === 'shared') return 'src/shared/' + srcRel;
      return null;
    }
    // shell
    if (c.kind === 'shell' || c.kind === 'shared') {
      return c.kind === 'shared' ? 'src/shared/' + srcRel : 'src/' + srcRel;
    }
    return null;
  };
  const queue = [];
  const enqueue = abs => {
    const d = destFor(abs);
    if (d && !copyMap.has(abs)) {
      copyMap.set(abs, d);
      queue.push(abs);
    }
    return d;
  };
  for (const abs of fileAbsList) enqueue(abs);
  while (queue.length) {
    const abs = queue.pop();
    const info = project.files.get(abs);
    if (!info) continue;
    for (const imp of info.imports) {
      if (!imp.source.startsWith('.')) continue;
      const target = resolveImport(abs, imp.source);
      if (!target) continue;
      if (copyMap.has(target)) continue;
      if (!enqueue(target)) {
        const srcRel = posix(path.relative(srcDir, target));
        const c = clusterOf(srcRel);
        cross.push({
          from: posix(path.relative(rootAbs, abs)),
          spec: imp.source,
          target: posix(path.relative(rootAbs, target)),
          targetKind: c.kind === 'feature' ? `feature "${c.name}"` : c.kind,
        });
      }
    }
  }
  // dedupe cross entries
  const seen = new Set();
  return {
    copyMap,
    cross: cross.filter(e => {
      const k = e.from + '\n' + e.spec + '\n' + e.target;
      if (seen.has(k)) return false;
      seen.add(k);
      return true;
    }),
  };
}

// ------------------------------------------------------------------ shell router
// In shell files that render <Routes>, rewrite relative imports of remote
// feature files into React.lazy federation imports. Everything else is left
// for the human (namespace imports, non-router files).
function rewriteShellRouter(code, abs, remoteOfFile) {
  let ast;
  try {
    ast = parse(code, abs);
  } catch {
    return { code, changed: false, notes: ['could not parse — copied as-is'], rewritten: [] };
  }
  if (!/<Routes[\s>]/.test(code)) return { code, changed: false, notes: [], rewritten: [] };
  const edits = [];
  const notes = [];
  const rewritten = []; // { spec, target } — imports converted to federation lazy
  let needsReact = !/from\s+['"]react['"]/.test(code);
  traverse(ast, {
    ImportDeclaration(p) {
      const src = p.node.source.value;
      if (!src.startsWith('.')) return;
      const target = resolveImport(abs, src);
      const remote = target && remoteOfFile(target);
      if (!remote) return;
      const specs = p.node.specifiers;
      if (specs.some(s => t.isImportNamespaceSpecifier(s))) {
        notes.push(
          `namespace import from '${src}' left as-is — convert to a named/default import or expose it from the '${remote}' remote`
        );
        return;
      }
      const lines = specs.map(s => {
        const local = s.local.name;
        const imported = t.isImportDefaultSpecifier(s) ? 'RemoteDefault' : s.imported.name;
        return `const ${local} = React.lazy(() => import('${remote}/Routes').then(m => ({ default: m['${imported}'] || m.RemoteDefault })));`;
      });
      edits.push({
        start: p.node.start,
        end: p.node.end,
        text:
          `// RVO-SPLIT: was \`import … from '${src}\` — now lazy-loads the '${remote}' remote.\n` +
          lines.join('\n'),
      });
      rewritten.push({ spec: src, target });
    },
  });
  if (!edits.length) return { code, changed: false, notes, rewritten };
  edits.sort((a, b) => b.start - a.start);
  let out = code;
  for (const e of edits) out = out.slice(0, e.start) + e.text + out.slice(e.end);
  if (needsReact) {
    out = `import React from 'react'; // RVO-SPLIT: added — needed for React.lazy wrappers below\n${out}`;
  }
  notes.push('wrap <Routes> in <React.Suspense fallback={…}> — lazy remotes need a suspense boundary');
  return { code: out, changed: true, notes, rewritten };
}

// ------------------------------------------------------------------ templates

function headerComment(kind, text) {
  if (kind === 'html') return `<!-- ${REVIEW}\n     ${text} -->\n`;
  if (kind === 'json-field') return undefined; // handled inline
  return `// ${REVIEW}\n// ${text}\n`;
}

function remoteViteConfig(remoteName, sharedDeps, port) {
  return (
    headerComment('js',
      `Module Federation config for the '${remoteName}' remote.\n` +
      `// 1. Run: npm i -D @originjs/vite-plugin-federation  (in this app)\n` +
      `// 2. Give every remote a unique dev port (server.port below).\n` +
      `// 3. After deploying, point the shell's remotes config at the deployed remoteEntry.js URL.`
    ) +
    `import { defineConfig } from 'vite';\n` +
    `import react from '@vitejs/plugin-react';\n` +
    `import federation from '@originjs/vite-plugin-federation';\n\n` +
    `export default defineConfig({\n` +
    `  plugins: [\n` +
    `    react(),\n` +
    `    federation({\n` +
    `      name: '${remoteName}',\n` +
    `      filename: 'remoteEntry.js',\n` +
    `      exposes: {\n` +
    `        './Routes': './src/remote-entry.jsx',\n` +
    `      },\n` +
    `      shared: [${sharedDeps.map(d => `'${d}'`).join(', ')}],\n` +
    `    }),\n` +
    `  ],\n` +
    `  server: { port: ${port} },\n` +
    `  build: { target: 'esnext', minify: false, cssCodeSplit: false },\n` +
    `});\n`
  );
}

function shellViteConfig(remotes, sharedDeps, remotePorts) {
  const entries = remotes
    .map(r => `      ${r.fedName}: 'http://localhost:${remotePorts[r.fedName]}/assets/remoteEntry.js',`)
    .join('\n');
  return (
    headerComment('js',
      `Module Federation config for the shell.\n` +
      `// 1. Run: npm i -D @originjs/vite-plugin-federation  (in this app)\n` +
      `// 2. Replace the localhost URLs below with your deployed remoteEntry.js URLs.`
    ) +
    `import { defineConfig } from 'vite';\n` +
    `import react from '@vitejs/plugin-react';\n` +
    `import federation from '@originjs/vite-plugin-federation';\n\n` +
    `export default defineConfig({\n` +
    `  plugins: [\n` +
    `    react(),\n` +
    `    federation({\n` +
    `      name: 'shell',\n` +
    `      remotes: {\n${entries}\n` +
    `      },\n` +
    `      shared: [${sharedDeps.map(d => `'${d}'`).join(', ')}],\n` +
    `    }),\n` +
    `  ],\n` +
    `  server: { port: 5000 },\n` +
    `  build: { target: 'esnext', minify: false, cssCodeSplit: false },\n` +
    `});\n`
  );
}

function appPackageJson(appName, pkg, port) {
  const deps = {};
  for (const d of ['react', 'react-dom', 'react-router-dom', 'react-router']) {
    const v =
      (pkg.dependencies && pkg.dependencies[d]) ||
      (pkg.devDependencies && pkg.devDependencies[d]);
    if (v) deps[d] = v;
  }
  if (!deps.react) deps.react = '^18.3.1';
  if (!deps['react-dom']) deps['react-dom'] = deps.react;
  return (
    JSON.stringify(
      {
        _rvo: `${REVIEW} Check deps, scripts and ports before use.`,
        name: appName,
        private: true,
        version: '0.0.0',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
        },
        dependencies: deps,
        devDependencies: {
          '@originjs/vite-plugin-federation': '^1.3.0',
          '@vitejs/plugin-react': '^4.0.0',
          vite: '^5.0.0',
        },
      },
      null,
      2
    ) + '\n'
  );
}

function indexHtml(title) {
  return (
    headerComment('html', 'Dev entry for this federated app.') +
    `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n` +
    `<title>${title}</title>\n</head>\n<body>\n<div id="root"></div>\n` +
    `<script type="module" src="/src/main.jsx"></script>\n</body>\n</html>\n`
  );
}

// ------------------------------------------------------------------ convert

function runSplitConvert(root, { planPath, out, dryRun = false } = {}) {
  if (!planPath) throw new Error('rvo split convert needs --plan <plan.json>.');
  let plan;
  try {
    plan = JSON.parse(fs.readFileSync(planPath, 'utf8'));
  } catch (e) {
    throw new Error(`Cannot read plan JSON at ${planPath}: ${e.message}`);
  }
  validatePlan(plan, planPath);

  const rootAbs = path.resolve(root);
  const resolvedOut = out ? path.resolve(out) : null;
  if (!dryRun && !resolvedOut)
    throw new Error('rvo split convert needs --out <dir> to write the monorepo (or use --dry-run to preview).');
  if (
    resolvedOut &&
    (resolvedOut === rootAbs || resolvedOut.startsWith(rootAbs + path.sep))
  )
    throw new Error('rvo split convert: --out must be outside the project root (source is never modified).');

  const config = loadConfig(rootAbs);
  const srcDir = path.join(rootAbs, config.srcDir);
  if (!fs.existsSync(srcDir)) throw new Error(`No source directory at ${srcDir}`);
  const project = buildProject(rootAbs, config);
  const pkg = readPkg(rootAbs);
  const sharedDeps = plan.sharedDeps && plan.sharedDeps.length ? plan.sharedDeps : ['react', 'react-dom'];

  const remotes = plan.remotes.map(r => ({ ...r, fedName: sanitizeName(r.name) }));
  const remotePorts = {};
  remotes.forEach((r, i) => {
    remotePorts[r.fedName] = 5001 + i;
  });
  // abs path of any feature file -> owning remote fedName (for shell rewrites)
  const featureFileToRemote = new Map();
  for (const r of remotes) {
    for (const f of r.files) featureFileToRemote.set(path.join(rootAbs, f), r.fedName);
  }
  const remoteOfFile = abs => featureFileToRemote.get(abs) || null;

  const ops = []; // { kind: 'copy'|'write', src?, dest, note? }
  const notes = []; // manual-work notes for MIGRATION-NOTES.md
  const allCross = [];

  const addCopy = (srcAbs, destAbs) => ops.push({ kind: 'copy', src: srcAbs, dest: destAbs });
  const addWrite = (destAbs, content, note) => ops.push({ kind: 'write', dest: destAbs, content, note });

  // --- remotes ---------------------------------------------------------------
  for (const remote of remotes) {
    const appDir = resolvedOut ? path.join(resolvedOut, remote.fedName) : path.join('<out>', remote.fedName);
    const fileAbsList = remote.files.map(f => path.join(rootAbs, f));
    const { copyMap, cross } = collectAppFiles({
      fileAbsList,
      srcDir,
      project,
      rootAbs,
      kind: 'remote',
      clusterName: remote.name.toLowerCase(),
    });
    allCross.push(...cross.map(c => ({ ...c, app: remote.fedName })));

    // copy + rewrite imports (targets resolved inside this remote's copy map)
    for (const [srcAbs, destRel] of copyMap) {
      const destAbs = resolvedOut ? path.join(appDir, destRel) : path.join(appDir, destRel);
      const code = fs.readFileSync(srcAbs, 'utf8');
      const { code: rewritten } = rewriteRelativeImports(code, srcAbs, destAbs, targetAbs => {
        const d = copyMap.get(targetAbs);
        return d ? path.join(appDir, d) : null;
      });
      addWrite(destAbs, rewritten);
    }

    // remote-entry.jsx — the public surface exposed as '<remote>/Routes'
    const entryAbs = path.join(rootAbs, remote.entry);
    const entryDestRel = copyMap.get(entryAbs);
    if (!entryDestRel) {
      notes.push(
        `Remote '${remote.fedName}': entry ${remote.entry} was not copied (outside the remote's cluster?) — wire exposes manually.`
      );
    } else {
      const entryInfo = project.files.get(entryAbs);
      const defaultName = entryInfo && entryInfo.defaultExportName;
      const entryImport = './' + posix(path.relative(path.dirname(path.join(appDir, 'src/remote-entry.jsx')), path.join(appDir, entryDestRel)));
      const entrySrc = `// ${REVIEW}
// Public surface of the '${remote.fedName}' remote, exposed to the shell as '${remote.fedName}/Routes'.
// Add or remove re-exports here as the remote's API evolves.
export * from '${entryImport}';
${defaultName ? `import ${defaultName}Default from '${entryImport}';\nexport { ${defaultName}Default as RemoteDefault };\n` : `// (entry has no default export — the shell falls back to named exports)\n`}`;
      addWrite(path.join(appDir, 'src/remote-entry.jsx'), entrySrc);
    }

    // standalone dev entry (lets the remote run on its own during development)
    addWrite(
      path.join(appDir, 'src/main.jsx'),
      `// ${REVIEW}\n// Standalone dev entry — renders this remote on its own (port ${remotePorts[remote.fedName]}).\n` +
        `// The shell consumes this remote via federation; this file is only for isolated development.\n` +
        `import React from 'react';\nimport ReactDOM from 'react-dom/client';\n` +
        `import { BrowserRouter } from 'react-router-dom';\nimport * as entry from './remote-entry.jsx';\n\n` +
        `const Routes = entry.RemoteDefault || entry[${JSON.stringify(capName(remote.name) + 'Routes')}] || Object.values(entry)[0];\n\n` +
        `ReactDOM.createRoot(document.getElementById('root')).render(\n` +
        `  <React.StrictMode>\n    <BrowserRouter>\n      <Routes />\n    </BrowserRouter>\n  </React.StrictMode>\n);\n`
    );

    addWrite(path.join(appDir, 'vite.config.js'), remoteViteConfig(remote.fedName, sharedDeps, remotePorts[remote.fedName]));
    addWrite(path.join(appDir, 'package.json'), appPackageJson(`rvo-${remote.fedName}-remote`, pkg));
    addWrite(path.join(appDir, 'index.html'), indexHtml(`${capName(remote.name)} (remote)`));
  }

  // --- shell ------------------------------------------------------------------
  const shellDir = resolvedOut ? path.join(resolvedOut, 'shell') : path.join('<out>', 'shell');
  const shellAbsList = plan.shell.files.map(f => path.join(rootAbs, f));
  const { copyMap: shellMap, cross: shellCross } = collectAppFiles({
    fileAbsList: shellAbsList,
    srcDir,
    project,
    rootAbs,
    kind: 'shell',
  });
  const shellRewritten = new Set(); // "fromRel\nspec" handled via federation lazy

  for (const [srcAbs, destRel] of shellMap) {
    const destAbs = path.join(shellDir, destRel);
    let code = fs.readFileSync(srcAbs, 'utf8');
    // 1. rewrite imports of copied (shared/shell) files
    code = rewriteRelativeImports(code, srcAbs, destAbs, targetAbs => {
      const d = shellMap.get(targetAbs);
      return d ? path.join(shellDir, d) : null;
    }).code;
    // 2. router files: lazy-load remote feature imports via federation
    //    (resolve against the SOURCE file — the output tree isn't on disk yet)
    const rw = rewriteShellRouter(code, srcAbs, remoteOfFile);
    if (rw.changed) {
      code = rw.code;
      const fromRel = posix(path.relative(rootAbs, srcAbs));
      for (const r of rw.rewritten) shellRewritten.add(fromRel + '\n' + r.spec);
    }
    if (rw.notes.length) {
      for (const n of rw.notes) notes.push(`shell/${destRel}: ${n}`);
    }
    addWrite(destAbs, code);
  }
  // Shell imports converted to federation lazy imports are resolved — don't
  // list them as manual cross-boundary work.
  const shellCrossFiltered = shellCross.filter(
    c => !shellRewritten.has(c.from + '\n' + c.spec)
  );
  allCross.push(...shellCrossFiltered.map(c => ({ ...c, app: 'shell' })));
  // root index.html → shell (dev entry)
  const rootIndex = path.join(rootAbs, 'index.html');
  if (fs.existsSync(rootIndex)) {
    addCopy(rootIndex, path.join(shellDir, 'index.html'));
  } else {
    addWrite(path.join(shellDir, 'index.html'), indexHtml('App shell'));
  }

  // federation.jsx — importable lazy wrappers for every remote
  const fedWrappers = remotes
    .map(
      r =>
        `export const ${capName(r.name)}Routes = React.lazy(() => import('${r.fedName}/Routes').then(m => ({ default: m.RemoteDefault || m['${capName(r.name)}Routes'] || Object.values(m)[0] })));`
    )
    .join('\n');
  addWrite(
    path.join(shellDir, 'src/federation.jsx'),
    `// ${REVIEW}\n// Lazy wrappers for each remote. Import these in the shell router\n// instead of importing feature files directly.\nimport React from 'react';\n\n${fedWrappers}\n`
  );

  // App.federated.jsx — suggested router adoption, filled in with real routes
  const fedRoutes = remotes
    .map(r => {
      const p = (r.routes && r.routes[0]) || `/${r.name}/*`;
      const routePath = p.endsWith('/*') ? p : p.replace(/\/?$/, '/*');
      return `        <Route path="${routePath}" element={<${capName(r.name)}Routes />} />`;
    })
    .join('\n');
  addWrite(
    path.join(shellDir, 'src/App.federated.jsx'),
    `// ${REVIEW}\n// Suggested federated router, generated from your split plan.\n` +
      `// Adopt this as your new App.jsx: keep your providers/auth wrappers from the\n// original App, replace the direct feature imports with the lazy remotes below.\n` +
      `import React, { Suspense } from 'react';\nimport { Routes, Route } from 'react-router-dom';\n` +
      `import {\n${remotes.map(r => `  ${capName(r.name)}Routes,`).join('\n')}\n} from './federation.jsx';\n\n` +
      `export default function App() {\n` +
      `  return (\n` +
      `    <Suspense fallback={<div>Loading…</div>}>\n` +
      `      <Routes>\n${fedRoutes}\n` +
      `        <Route path="*" element={<div>Not found</div>} />\n` +
      `      </Routes>\n` +
      `    </Suspense>\n` +
      `  );\n}\n`
  );

  addWrite(path.join(shellDir, 'vite.config.js'), shellViteConfig(remotes, sharedDeps, remotePorts));
  addWrite(path.join(shellDir, 'package.json'), appPackageJson('rvo-shell', pkg));

  // --- MIGRATION-NOTES.md ---------------------------------------------------------
  const portRows = [`| App | Dev port | Remote entry |`, `| --- | --- | --- |`];
  for (const r of remotes) {
    portRows.push(`| ${r.fedName} | ${remotePorts[r.fedName]} | http://localhost:${remotePorts[r.fedName]}/assets/remoteEntry.js |`);
  }
  portRows.push(`| shell | 5000 | — |`);
  const crossLines = allCross.length
    ? allCross.map(
        c => `- \`${c.app}\`: \`${c.from}\` imports \`${c.spec}\` → \`${c.target}\` (${c.targetKind}); not copied — extract to shared or expose via federation`
      )
    : ['- None — all relative imports resolved inside their own app.'];
  const riskLines = (plan.risks || []).map(r => `- ${r}`);
  addWrite(
    path.join(resolvedOut || '<out>', 'MIGRATION-NOTES.md'),
    `# Migration notes — rvo split convert\n\n` +
      `Generated ${new Date().toISOString()} from \`${planPath}\`. ` +
      `Review every file marked \`${REVIEW}\` before running anything.\n\n` +
      `## 1. Install the federation plugin (manual — one per app)\n\n` +
      `\`\`\`bash\n` +
      [...remotes.map(r => `cd ${r.fedName} && npm i -D @originjs/vite-plugin-federation`), `cd shell && npm i -D @originjs/vite-plugin-federation`].join('\n') +
      `\n\`\`\`\n` +
      `rvo does not add this dependency for you — it changes your build, so it stays a conscious step.\n\n` +
      `## 2. Dev ports\n\n${portRows.join('\n')}\n\n` +
      `## 3. Wire the shell router\n\n` +
      `- The shell's router file(s) had direct feature imports rewritten to \`React.lazy(() => import('<remote>/Routes'))\`.\n` +
      `- Review \`shell/src/App.federated.jsx\` — the suggested adoption, pre-filled with your real routes — and make it your new \`App.jsx\` (keeping providers/auth wrappers).\n` +
      `- \`shell/src/federation.jsx\` holds importable lazy wrappers for every remote.\n` +
      `- Wrap \`<Routes>\` in \`<React.Suspense>\` (lazy remotes need a suspense boundary).\n\n` +
      `## 4. Deploy remotes, then update the shell\n\n` +
      `- Deploy each remote; replace the localhost URLs in \`shell/vite.config.js\` → \`remotes\` with the deployed \`remoteEntry.js\` URLs.\n` +
      `- Keep \`shared\` (react, react-dom, …) version-aligned across apps or you will load two Reacts.\n\n` +
      `## 5. Cross-boundary imports to resolve by hand\n\n${crossLines.join('\n')}\n\n` +
      (riskLines.length ? `## 6. Risks carried over from analysis\n\n${riskLines.join('\n')}\n\n` : '') +
      `## What rvo did NOT do\n\n` +
      `- No state migration: shared Context/stores were copied into each app that needs them. For true singletons, extract them into a shared federation module.\n` +
      `- No CSS strategy: global styles were copied; consider CSS modules or a design-token package to avoid collisions.\n` +
      `- No auth/routing guards: shell-level concerns stay your code.\n` +
      `- No tests were ported.\n`
  );

  // --- execute or preview ----------------------------------------------------------
  if (dryRun) {
    printDryRun(ops, resolvedOut || '<out>');
    return { dryRun: true, ops };
  }
  for (const op of ops) {
    fs.mkdirSync(path.dirname(op.dest), { recursive: true });
    if (op.kind === 'copy') fs.copyFileSync(op.src, op.dest);
    else fs.writeFileSync(op.dest, op.content);
  }
  printSummary(ops, resolvedOut, remotes, notes);
  return { ops, out: resolvedOut, notes };
}

function printDryRun(ops, outDir) {
  console.log(chalk.bold.cyan('\nrvo split convert — dry run (no files written)'));
  console.log(chalk.dim(`  target: ${outDir}\n`));
  const copies = ops.filter(o => o.kind === 'copy');
  const writes = ops.filter(o => o.kind === 'write');
  for (const op of ops) {
    if (op.kind === 'copy') {
      console.log(`  ${chalk.dim('copy ')} ${op.src} → ${op.dest}`);
    } else {
      console.log(`  ${chalk.green('write')} ${op.dest}`);
    }
  }
  console.log(
    chalk.dim(`\n  ${copies.length} copies, ${writes.length} generated files. Re-run without --dry-run to write.`)
  );
}

function printSummary(ops, outDir, remotes, notes) {
  const writes = ops.filter(o => o.kind === 'write').length;
  const copies = ops.filter(o => o.kind === 'copy').length;
  console.log(chalk.bold.green('\n✓ Microfrontend monorepo generated'));
  console.log(chalk.dim(`  ${outDir}`));
  console.log(`  ${chalk.bold(remotes.length)} remote(s): ${remotes.map(r => r.fedName).join(', ')}`);
  console.log(`  shell + MIGRATION-NOTES.md`);
  console.log(chalk.dim(`  ${copies} files copied, ${writes} files generated.`));
  if (notes.length) {
    console.log(chalk.yellow('\n  Manual review needed:'));
    const shown = notes.slice(0, 8);
    for (const n of shown) console.log(chalk.yellow(`    ! ${n}`));
    if (notes.length > shown.length)
      console.log(chalk.dim(`    …and ${notes.length - shown.length} more — see MIGRATION-NOTES.md`));
  }
  console.log(
    chalk.dim('\n  Next: read MIGRATION-NOTES.md, install @originjs/vite-plugin-federation per app, run each dev server.')
  );
}

module.exports = { runSplitConvert, validatePlan, sanitizeName };
